version: '2'

services:

  ## Minimum arguments setup
  vtiger:
    build: ${VERSION}
    image: vtiger:${VERSION}
    links: ['mysql']
    environment: ['MYSQL_HOST=mysql', 'MYSQL_ROOT_PASSWORD=Pa$$w0rd']
  mysql:
    image: mysql:5.5
    volumes: ['mysql:/var/lib/mysql:rw']
    environment: ['MYSQL_ROOT_PASSWORD=Pa$$w0rd']

  ## Non-root mysql user
  vtiger-non-root:
    image: vtiger:${VERSION}
    links: ['mysql-non-root']
    environment: ['MYSQL_HOST=mysql', 'MYSQL_USER=vtiger', 'MYSQL_PASSWORD=Pa$$w0rd']
  mysql-non-root:
    image: mysql:5.5
    volumes: ['mysql-non-root:/var/lib/mysql:rw']
    environment: ['MYSQL_USER=vtiger', 'MYSQL_PASSWORD=Pa$$w0rd']

volumes:
  mysql:
  mysql-non-root:
