version: '2'

services:

  vtiger:
    build: ${version}
    environment:
      - VT_DEBUG=true
#     - LOG4PHP_DEBUG=true
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - 20080:80
      - 20443:443
    volumes:
      - ./vtiger:/var/lib/vtiger
#     - ./phpinfo.php:/var/www/html/phpinfo.php
#     - ./config.inc.php:/var/www/html/config.inc.php
#     - ./vtiger-foreground.sh:/usr/local/bin/vtiger-foreground.sh
    links:
      - mysql
      - adminer

  adminer:
    image: javanile/adminer
    environment:
      - MYSQL_DATABASE=vtiger
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - 20081:8080
    links:
      - mysql

  mysql:
    image: mysql:5.5
    environment:
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      - mysql:/var/lib/mysql:rw
      - ./:/vtiger:rw

  clean:
    image: debian
    working_dir: /vtiger
    entrypoint:
      - /vtiger/clean.sh
    volumes:
      - ./:/vtiger:rw

  update:
    image: debian
    working_dir: /vtiger
    entrypoint:
      - /vtiger/update.sh
    volumes:
      - ./:/vtiger:rw

volumes:
  mysql:
