version: '2'

services:

  ## Minimum arguments setup
  vtiger:
    { build: ${VERSION}, image: vtiger, links: ['mysql'],
      environment: ['MYSQL_HOST=mysql', 'MYSQL_ROOT_PASSWORD=Pa$$w0rd'] }
  mysql:
    { image: mysql:5.5, volumes: ['mysql:/var/lib/mysql:rw'],
      environment: ['MYSQL_ROOT_PASSWORD=Pa$$w0rd'] }


  vtiger-no-root:
    image: vtiger
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_ROOT_PASSWORD=Pa$$w0rd
    links:
      - mysql-no-root

  mysql-no-root:
    image: mysql:5.5
    environment:
      - MYSQL_USER=vtiger
      - MYSQL_PASSWORD=Pa$$w0rd
    volumes:
      - mysql-no-root:/var/lib/mysql:rw


volumes:
  mysql:
  mysql-no-root: