version: '2'

services:

  vtiger:
    build: ${VERSION}
    environment:
      - VT_DEBUG=true
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - "20080:80"
      - "20443:443"
    volumes:
      #- ./config.inc.php:/var/www/html/vtiger/config.inc.php
      - ./phpinfo.php:/var/www/html/vtiger/phpinfo.php
      - ./vtiger-foreground.sh:/usr/local/bin/vtiger-foreground.sh
      - ./volumes/logs:/var/www/html/vtiger/logs
      - ./volumes/storage:/var/www/html/vtiger/storage
    links:
      - mysql
      - adminer

  adminer:
    image: javanile/adminer
    environment:
      - MYSQL_DATABASE=vtiger
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - "20081:8080"
    links:
      - mysql

  mysql:
    image: mysql:5.5
    environment:
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      - mysql:/var/lib/mysql:rw
      - ./:/vtiger:rw

  update:
    image: debian
    working_dir: /vtiger
    entrypoint: ['/vtiger/update.sh']
    volumes:
      - ./:/vtiger:rw

volumes:
  mysql:
